samples:
  - GSE141044

# Quality control thresholds
qc:
  hvg: 2000        # minimum genes detected per cell
  min_cells: 3     # maximum genes detected per cell

# Optional batch labels (if batch correction across samples)
batches:
  GSE141044: sample_id
cell_types:
  GSE141044: leiden
conditions:
  GSE141044: age
classes:
  GSE141044: genotype