samples:
  - GSE141044

# Quality control thresholds
qc:
  min_genes: 200        # minimum genes detected per cell
  min_cells: 3       # maximum genes detected per cell
  max_pct_mt: 5         # maximum mitochondrial gene percentage

# Optional batch labels (if batch correction across samples)
batches:
  GSE141044: sample_id